esphome:
  name: ustepper
  friendly_name: uStepper

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Disable logging
logger:
  baud_rate: 9600

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "uStepper Fallback Hotspot"
    password: ""

captive_portal:

uart:
  id: uart_modbus
  rx_pin: 20
  tx_pin: 21
  baud_rate: 9600

modbus:
  id: modbus1
  uart_id: uart_modbus

modbus_controller:
  - id: modbus_device
    modbus_id: modbus1
    address: 0x01  # Address of the Modbus slave device
    update_interval: 1s


select:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Set mode"
    id: ustepper_set_mode
    address: 17
    value_type: U_WORD
    optionsmap:
      "Absolute Angle" : 0
      "Speed" : 1
      "Relative Steps" : 2
      "Relative Angle" : 3

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Set brake mode"
    id: ustepper_set_brakemode
    address: 16
    value_type: U_WORD
    optionsmap:
      "Freewheel" : 0
      "Cool brake" : 1
      "Hard brake" : 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Set loop mode"
    id: ustepper_set_loopmode
    address: 22
    value_type: U_WORD
    optionsmap:
      "Open loop" : 0
      "Closed loop" : 1 

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Driver RPM"
    register_type: holding
    address: 0x0002
    value_type: FP32_R
    unit_of_measurement: "RPM"
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Motor State"
    register_type: holding
    address: 0x0006
    value_type: U_WORD
    unit_of_measurement: ""
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Angle Moved"
    register_type: holding
    address: 0x0000
    value_type: FP32_R
    unit_of_measurement: "°"
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Encoder RPM"
    register_type: holding
    address: 0x0004
    value_type: FP32_R
    unit_of_measurement: "RPM"
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Is Stalled"
    register_type: holding
    address: 0x0007
    value_type: U_WORD
    unit_of_measurement: ""
    accuracy_decimals: 0

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Set RPM"
    register_type: holding
    address: 10
    value_type: FP32_R
    min_value: -1000.0
    max_value: 1000.0
    step: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Move Steps"
    register_type: holding
    address: 12
    value_type: FP32_R
    min_value: -32768
    max_value: 32767
    step: 1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Move Angle"
    register_type: holding
    address: 14
    value_type: FP32_R
    min_value: 0.0
    max_value: 3600.0
    step: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Move to Angle"
    register_type: holding
    address: 8
    value_type: FP32_R
    min_value: -36000.0
    max_value: 36000.0
    step: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Max velocity RPM"
    register_type: holding
    address: 20
    value_type: FP32_R
    min_value: 0.0
    max_value: 1000.0
    step: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Max acceleration Rev/s^2"
    register_type: holding
    address: 18
    value_type: FP32_R
    min_value: 0.0
    max_value: 330.0
    step: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Run current"
    register_type: holding
    address: 24
    value_type: U_WORD
    min_value: 0
    max_value: 100
    unit_of_measurement: "%"
    step: 1
